# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vla_pb2 as vla__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vla_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VlaServerStub:
    """---- 服务 ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResetWorld = channel.unary_unary(
                '/vla.VlaServer/ResetWorld',
                request_serializer=vla__pb2.ResetRequest.SerializeToString,
                response_deserializer=vla__pb2.ResetReply.FromString,
                _registered_method=True)
        self.GetStepResult = channel.unary_unary(
                '/vla.VlaServer/GetStepResult',
                request_serializer=vla__pb2.StepRequest.SerializeToString,
                response_deserializer=vla__pb2.StepReply.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/vla.VlaServer/GetState',
                request_serializer=vla__pb2.StateRequest.SerializeToString,
                response_deserializer=vla__pb2.StateReply.FromString,
                _registered_method=True)
        self.GetVoxels = channel.unary_unary(
                '/vla.VlaServer/GetVoxels',
                request_serializer=vla__pb2.VoxelRequest.SerializeToString,
                response_deserializer=vla__pb2.VoxelReply.FromString,
                _registered_method=True)
        self.ComputePath = channel.unary_unary(
                '/vla.VlaServer/ComputePath',
                request_serializer=vla__pb2.PathRequest.SerializeToString,
                response_deserializer=vla__pb2.PathReply.FromString,
                _registered_method=True)
        self.SetTask = channel.unary_unary(
                '/vla.VlaServer/SetTask',
                request_serializer=vla__pb2.TaskRequest.SerializeToString,
                response_deserializer=vla__pb2.TaskReply.FromString,
                _registered_method=True)
        self.GenerateTask = channel.unary_unary(
                '/vla.VlaServer/GenerateTask',
                request_serializer=vla__pb2.GenerateRequest.SerializeToString,
                response_deserializer=vla__pb2.TaskReply.FromString,
                _registered_method=True)
        self.ClearRegion = channel.unary_unary(
                '/vla.VlaServer/ClearRegion',
                request_serializer=vla__pb2.ClearRequest.SerializeToString,
                response_deserializer=vla__pb2.Void.FromString,
                _registered_method=True)
        self.Teleport = channel.unary_unary(
                '/vla.VlaServer/Teleport',
                request_serializer=vla__pb2.TeleportRequest.SerializeToString,
                response_deserializer=vla__pb2.Void.FromString,
                _registered_method=True)
        self.SpawnEntity = channel.unary_unary(
                '/vla.VlaServer/SpawnEntity',
                request_serializer=vla__pb2.SpawnRequest.SerializeToString,
                response_deserializer=vla__pb2.Void.FromString,
                _registered_method=True)
        self.SetBlock = channel.unary_unary(
                '/vla.VlaServer/SetBlock',
                request_serializer=vla__pb2.SetBlockRequest.SerializeToString,
                response_deserializer=vla__pb2.Void.FromString,
                _registered_method=True)


class VlaServerServicer:
    """---- 服务 ----

    """

    def ResetWorld(self, request, context):
        """重置世界与任务（主线程执行，§4.2）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStepResult(self, request, context):
        """阻塞等待 k ticks 后结算 reward/done/progress（server-authoritative）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """玩家/背包/统计等本地状态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoxels(self, request, context):
        """32³ 体素矩阵（只读，可 gRPC 线程直读）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputePath(self, request, context):
        """3D A* 航点（只读）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTask(self, request, context):
        """设置任务。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTask(self, request, context):
        """课程/LLM 生成任务。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearRegion(self, request, context):
        """清空区域实体/方块。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teleport(self, request, context):
        """传送玩家。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpawnEntity(self, request, context):
        """生成实体。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBlock(self, request, context):
        """设置方块（God Mode）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VlaServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResetWorld': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetWorld,
                    request_deserializer=vla__pb2.ResetRequest.FromString,
                    response_serializer=vla__pb2.ResetReply.SerializeToString,
            ),
            'GetStepResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStepResult,
                    request_deserializer=vla__pb2.StepRequest.FromString,
                    response_serializer=vla__pb2.StepReply.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=vla__pb2.StateRequest.FromString,
                    response_serializer=vla__pb2.StateReply.SerializeToString,
            ),
            'GetVoxels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVoxels,
                    request_deserializer=vla__pb2.VoxelRequest.FromString,
                    response_serializer=vla__pb2.VoxelReply.SerializeToString,
            ),
            'ComputePath': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputePath,
                    request_deserializer=vla__pb2.PathRequest.FromString,
                    response_serializer=vla__pb2.PathReply.SerializeToString,
            ),
            'SetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTask,
                    request_deserializer=vla__pb2.TaskRequest.FromString,
                    response_serializer=vla__pb2.TaskReply.SerializeToString,
            ),
            'GenerateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTask,
                    request_deserializer=vla__pb2.GenerateRequest.FromString,
                    response_serializer=vla__pb2.TaskReply.SerializeToString,
            ),
            'ClearRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearRegion,
                    request_deserializer=vla__pb2.ClearRequest.FromString,
                    response_serializer=vla__pb2.Void.SerializeToString,
            ),
            'Teleport': grpc.unary_unary_rpc_method_handler(
                    servicer.Teleport,
                    request_deserializer=vla__pb2.TeleportRequest.FromString,
                    response_serializer=vla__pb2.Void.SerializeToString,
            ),
            'SpawnEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnEntity,
                    request_deserializer=vla__pb2.SpawnRequest.FromString,
                    response_serializer=vla__pb2.Void.SerializeToString,
            ),
            'SetBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBlock,
                    request_deserializer=vla__pb2.SetBlockRequest.FromString,
                    response_serializer=vla__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vla.VlaServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vla.VlaServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VlaServer:
    """---- 服务 ----

    """

    @staticmethod
    def ResetWorld(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/ResetWorld',
            vla__pb2.ResetRequest.SerializeToString,
            vla__pb2.ResetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStepResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/GetStepResult',
            vla__pb2.StepRequest.SerializeToString,
            vla__pb2.StepReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/GetState',
            vla__pb2.StateRequest.SerializeToString,
            vla__pb2.StateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVoxels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/GetVoxels',
            vla__pb2.VoxelRequest.SerializeToString,
            vla__pb2.VoxelReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/ComputePath',
            vla__pb2.PathRequest.SerializeToString,
            vla__pb2.PathReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/SetTask',
            vla__pb2.TaskRequest.SerializeToString,
            vla__pb2.TaskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/GenerateTask',
            vla__pb2.GenerateRequest.SerializeToString,
            vla__pb2.TaskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/ClearRegion',
            vla__pb2.ClearRequest.SerializeToString,
            vla__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Teleport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/Teleport',
            vla__pb2.TeleportRequest.SerializeToString,
            vla__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpawnEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/SpawnEntity',
            vla__pb2.SpawnRequest.SerializeToString,
            vla__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VlaServer/SetBlock',
            vla__pb2.SetBlockRequest.SerializeToString,
            vla__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
